// Code generated by ent, DO NOT EDIT.

package rest

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/lrstanley/entrest/_examples/kitchensink/internal/database/ent"
	"github.com/lrstanley/entrest/_examples/kitchensink/internal/database/ent/pet"
)

// ReplacePetParams defines parameters for replacing a Pet via a PUT request.
// Only includes fields/edges not excluded from replace operations.
// Replace performs full resource replacement: unprovided optional fields are cleared (set to nil).
type ReplacePetParams struct {
	Name      string   `json:"name"`
	Nicknames []string `json:"nicknames,omitempty"`
	// Optional description of the pet.
	Description *string  `json:"description,omitempty"`
	Age         int      `json:"age"`
	Type        pet.Type `json:"type"`
	// Categories that the pet belongs to.
	Categories []int `json:"categories,omitempty"`
	// The user that owns the pet.
	Owner *uuid.UUID `json:"owner,omitempty"`
	// Pets that this pet is friends with.
	Friends []int `json:"friends,omitempty"`
	// Users that this pet is followed by.
	FollowedBy []uuid.UUID `json:"followed_by,omitempty"`
}

func (r *ReplacePetParams) ApplyInputs(builder *ent.PetCreate) *ent.PetCreate {
	builder.SetName(r.Name)
	if r.Nicknames != nil {
		builder.SetNicknames(r.Nicknames)
	}
	if r.Description != nil {
		builder.SetDescription(*r.Description)
	}
	builder.SetAge(r.Age)
	builder.SetType(r.Type)
	if r.Owner != nil {
		builder.SetOwnerID(*r.Owner)
	}
	return builder
}

// Exec wraps all logic (mapping all provided values to the builder), replaces the entity
// (creating it if it doesn't exist or fully replacing it if it does), and does another query
// (using provided query as base) to get the entity, with all eager loaded edges.
func (r *ReplacePetParams) Exec(ctx context.Context, id int, builder *ent.PetCreate, query *ent.PetQuery, updater *ent.PetUpdateOne) (*ent.Pet, error) {
	// Set the ID for the replace operation
	builder.SetID(id)

	// Apply all inputs from the params
	builder = r.ApplyInputs(builder)

	// Perform replace with OnConflict - full replacement mode (true PUT semantics)
	// Unprovided optional/nullable fields are explicitly cleared
	err := builder.OnConflictColumns(pet.FieldID).Update(func(u *ent.PetUpsert) {
		u.SetName(r.Name)
		if r.Nicknames != nil {
			u.SetNicknames(r.Nicknames)
		} else {
			u.ClearNicknames()
		}
		if r.Description != nil {
			u.SetDescription(*r.Description)
		} else {
			u.ClearDescription()
		}
		u.SetAge(r.Age)
		u.SetType(r.Type)
	}).Exec(ctx)
	if err != nil {
		return nil, err
	}
	{
		// Always clear (Replace means full replacement - unprovided fields are cleared)
		edgeUpdater := updater.ClearCategories()
		if len(r.Categories) > 0 {
			// Add the new edge IDs if provided
			edgeUpdater = edgeUpdater.AddCategoryIDs(r.Categories...)
		}
		// If empty array or omitted, just clear (don't add anything)
		err = edgeUpdater.Exec(ctx)
		if err != nil {
			return nil, err
		}
	}
	{
		// Always clear (Replace means full replacement - unprovided fields are cleared)
		edgeUpdater := updater.ClearFriends()
		if len(r.Friends) > 0 {
			// Add the new edge IDs if provided
			edgeUpdater = edgeUpdater.AddFriendIDs(r.Friends...)
		}
		// If empty array or omitted, just clear (don't add anything)
		err = edgeUpdater.Exec(ctx)
		if err != nil {
			return nil, err
		}
	}
	{
		// Always clear (Replace means full replacement - unprovided fields are cleared)
		edgeUpdater := updater.ClearFollowedBy()
		if len(r.FollowedBy) > 0 {
			// Add the new edge IDs if provided
			edgeUpdater = edgeUpdater.AddFollowedByIDs(r.FollowedBy...)
		}
		// If empty array or omitted, just clear (don't add anything)
		err = edgeUpdater.Exec(ctx)
		if err != nil {
			return nil, err
		}
	}

	// Fetch the entity with eager-loaded edges
	return EagerLoadPet(query.Where(pet.ID(id))).Only(ctx)
}
