// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lrstanley/entrest/_examples/kitchensink/internal/database/ent/follows"
	"github.com/lrstanley/entrest/_examples/kitchensink/internal/database/ent/pet"
	"github.com/lrstanley/entrest/_examples/kitchensink/internal/database/ent/user"
)

// FollowsCreate is the builder for creating a Follows entity.
type FollowsCreate struct {
	config
	mutation *FollowsMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetFollowedAt sets the "followed_at" field.
func (_c *FollowsCreate) SetFollowedAt(v time.Time) *FollowsCreate {
	_c.mutation.SetFollowedAt(v)
	return _c
}

// SetNillableFollowedAt sets the "followed_at" field if the given value is not nil.
func (_c *FollowsCreate) SetNillableFollowedAt(v *time.Time) *FollowsCreate {
	if v != nil {
		_c.SetFollowedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *FollowsCreate) SetUserID(v uuid.UUID) *FollowsCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPetID sets the "pet_id" field.
func (_c *FollowsCreate) SetPetID(v int) *FollowsCreate {
	_c.mutation.SetPetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *FollowsCreate) SetUser(v *User) *FollowsCreate {
	return _c.SetUserID(v.ID)
}

// SetPet sets the "pet" edge to the Pet entity.
func (_c *FollowsCreate) SetPet(v *Pet) *FollowsCreate {
	return _c.SetPetID(v.ID)
}

// Mutation returns the FollowsMutation object of the builder.
func (_c *FollowsCreate) Mutation() *FollowsMutation {
	return _c.mutation
}

// Save creates the Follows in the database.
func (_c *FollowsCreate) Save(ctx context.Context) (*Follows, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FollowsCreate) SaveX(ctx context.Context) *Follows {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FollowsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FollowsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FollowsCreate) defaults() {
	if _, ok := _c.mutation.FollowedAt(); !ok {
		v := follows.DefaultFollowedAt()
		_c.mutation.SetFollowedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FollowsCreate) check() error {
	if _, ok := _c.mutation.FollowedAt(); !ok {
		return &ValidationError{Name: "followed_at", err: errors.New(`ent: missing required field "Follows.followed_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Follows.user_id"`)}
	}
	if _, ok := _c.mutation.PetID(); !ok {
		return &ValidationError{Name: "pet_id", err: errors.New(`ent: missing required field "Follows.pet_id"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Follows.user"`)}
	}
	if len(_c.mutation.PetIDs()) == 0 {
		return &ValidationError{Name: "pet", err: errors.New(`ent: missing required edge "Follows.pet"`)}
	}
	return nil
}

func (_c *FollowsCreate) sqlSave(ctx context.Context) (*Follows, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *FollowsCreate) createSpec() (*Follows, *sqlgraph.CreateSpec) {
	var (
		_node = &Follows{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(follows.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.FollowedAt(); ok {
		_spec.SetField(follows.FieldFollowedAt, field.TypeTime, value)
		_node.FollowedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   follows.UserTable,
			Columns: []string{follows.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   follows.PetTable,
			Columns: []string{follows.PetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PetID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Follows.Create().
//		SetFollowedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FollowsUpsert) {
//			SetFollowedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *FollowsCreate) OnConflict(opts ...sql.ConflictOption) *FollowsUpsertOne {
	_c.conflict = opts
	return &FollowsUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Follows.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FollowsCreate) OnConflictColumns(columns ...string) *FollowsUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FollowsUpsertOne{
		create: _c,
	}
}

type (
	// FollowsUpsertOne is the builder for "upsert"-ing
	//  one Follows node.
	FollowsUpsertOne struct {
		create *FollowsCreate
	}

	// FollowsUpsert is the "OnConflict" setter.
	FollowsUpsert struct {
		*sql.UpdateSet
	}
)

// SetFollowedAt sets the "followed_at" field.
func (u *FollowsUpsert) SetFollowedAt(v time.Time) *FollowsUpsert {
	u.Set(follows.FieldFollowedAt, v)
	return u
}

// UpdateFollowedAt sets the "followed_at" field to the value that was provided on create.
func (u *FollowsUpsert) UpdateFollowedAt() *FollowsUpsert {
	u.SetExcluded(follows.FieldFollowedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *FollowsUpsert) SetUserID(v uuid.UUID) *FollowsUpsert {
	u.Set(follows.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *FollowsUpsert) UpdateUserID() *FollowsUpsert {
	u.SetExcluded(follows.FieldUserID)
	return u
}

// SetPetID sets the "pet_id" field.
func (u *FollowsUpsert) SetPetID(v int) *FollowsUpsert {
	u.Set(follows.FieldPetID, v)
	return u
}

// UpdatePetID sets the "pet_id" field to the value that was provided on create.
func (u *FollowsUpsert) UpdatePetID() *FollowsUpsert {
	u.SetExcluded(follows.FieldPetID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Follows.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FollowsUpsertOne) UpdateNewValues() *FollowsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Follows.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FollowsUpsertOne) Ignore() *FollowsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FollowsUpsertOne) DoNothing() *FollowsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FollowsCreate.OnConflict
// documentation for more info.
func (u *FollowsUpsertOne) Update(set func(*FollowsUpsert)) *FollowsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FollowsUpsert{UpdateSet: update})
	}))
	return u
}

// SetFollowedAt sets the "followed_at" field.
func (u *FollowsUpsertOne) SetFollowedAt(v time.Time) *FollowsUpsertOne {
	return u.Update(func(s *FollowsUpsert) {
		s.SetFollowedAt(v)
	})
}

// UpdateFollowedAt sets the "followed_at" field to the value that was provided on create.
func (u *FollowsUpsertOne) UpdateFollowedAt() *FollowsUpsertOne {
	return u.Update(func(s *FollowsUpsert) {
		s.UpdateFollowedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *FollowsUpsertOne) SetUserID(v uuid.UUID) *FollowsUpsertOne {
	return u.Update(func(s *FollowsUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *FollowsUpsertOne) UpdateUserID() *FollowsUpsertOne {
	return u.Update(func(s *FollowsUpsert) {
		s.UpdateUserID()
	})
}

// SetPetID sets the "pet_id" field.
func (u *FollowsUpsertOne) SetPetID(v int) *FollowsUpsertOne {
	return u.Update(func(s *FollowsUpsert) {
		s.SetPetID(v)
	})
}

// UpdatePetID sets the "pet_id" field to the value that was provided on create.
func (u *FollowsUpsertOne) UpdatePetID() *FollowsUpsertOne {
	return u.Update(func(s *FollowsUpsert) {
		s.UpdatePetID()
	})
}

// Exec executes the query.
func (u *FollowsUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FollowsCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FollowsUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// FollowsCreateBulk is the builder for creating many Follows entities in bulk.
type FollowsCreateBulk struct {
	config
	err      error
	builders []*FollowsCreate
	conflict []sql.ConflictOption
}

// Save creates the Follows entities in the database.
func (_c *FollowsCreateBulk) Save(ctx context.Context) ([]*Follows, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Follows, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FollowsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FollowsCreateBulk) SaveX(ctx context.Context) []*Follows {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FollowsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FollowsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Follows.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FollowsUpsert) {
//			SetFollowedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *FollowsCreateBulk) OnConflict(opts ...sql.ConflictOption) *FollowsUpsertBulk {
	_c.conflict = opts
	return &FollowsUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Follows.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FollowsCreateBulk) OnConflictColumns(columns ...string) *FollowsUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FollowsUpsertBulk{
		create: _c,
	}
}

// FollowsUpsertBulk is the builder for "upsert"-ing
// a bulk of Follows nodes.
type FollowsUpsertBulk struct {
	create *FollowsCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Follows.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FollowsUpsertBulk) UpdateNewValues() *FollowsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Follows.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FollowsUpsertBulk) Ignore() *FollowsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FollowsUpsertBulk) DoNothing() *FollowsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FollowsCreateBulk.OnConflict
// documentation for more info.
func (u *FollowsUpsertBulk) Update(set func(*FollowsUpsert)) *FollowsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FollowsUpsert{UpdateSet: update})
	}))
	return u
}

// SetFollowedAt sets the "followed_at" field.
func (u *FollowsUpsertBulk) SetFollowedAt(v time.Time) *FollowsUpsertBulk {
	return u.Update(func(s *FollowsUpsert) {
		s.SetFollowedAt(v)
	})
}

// UpdateFollowedAt sets the "followed_at" field to the value that was provided on create.
func (u *FollowsUpsertBulk) UpdateFollowedAt() *FollowsUpsertBulk {
	return u.Update(func(s *FollowsUpsert) {
		s.UpdateFollowedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *FollowsUpsertBulk) SetUserID(v uuid.UUID) *FollowsUpsertBulk {
	return u.Update(func(s *FollowsUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *FollowsUpsertBulk) UpdateUserID() *FollowsUpsertBulk {
	return u.Update(func(s *FollowsUpsert) {
		s.UpdateUserID()
	})
}

// SetPetID sets the "pet_id" field.
func (u *FollowsUpsertBulk) SetPetID(v int) *FollowsUpsertBulk {
	return u.Update(func(s *FollowsUpsert) {
		s.SetPetID(v)
	})
}

// UpdatePetID sets the "pet_id" field to the value that was provided on create.
func (u *FollowsUpsertBulk) UpdatePetID() *FollowsUpsertBulk {
	return u.Update(func(s *FollowsUpsert) {
		s.UpdatePetID()
	})
}

// Exec executes the query.
func (u *FollowsUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FollowsCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FollowsCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FollowsUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
